<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Motiva.Application\Motiva.Application.csproj" />
    <ProjectReference Include="..\..\src\Motiva.Infrastructure\Motiva.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
  </ItemGroup>
</Project>
